### ISSUE TITLE
What next??

### ISSUE THREAD

**Issue by Riv67** [Riv67/responsive-typography#1]
Hi @thomasjbradley , I tried to apply what you told me about the size classifications of the different sections/media queries. I made the line-height and margins 1.3 in the main part, 1.4 in the first media query, 1.5 in the next, etc. I’m not sure if i did it right, because it doesn’t seems any better. And I added margins/padding that are 0rem because it made it look more like the screenshot, but i know that must be wrong because markbot doesn’t like it. So now i’m confused and not sure what else to do. (also- markbot says the line-height in the 60em media query is wrong, and the margin in line 33 is wrong, even though i thought i was following your advice - see screenshot) 

![Screenshot 2019-11-13 16 40 59](https://user-images.githubusercontent.com/55094177/68806720-645b6a00-0634-11ea-837a-e5229e99a87e.png)

**Comment by thomasjbradley** [comment]
Did you figure this out? It looks good to me.

**Comment by Riv67** [comment]
Ah yes, got some help at lab time:) thx!
